version: '3'
services:
  mariadb:
    image: 'bitnami/mariadb:10.1.38-debian-9-r33'
    environment:
      - MARIADB_USER=bn_opencart
      - MARIADB_DATABASE=bitnami_opencart
      - ALLOW_EMPTY_PASSWORD=yes

  opencart:
    image: 'bitnami/opencart:3.0.3-1-debian-9-r55'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=bn_opencart
      - OPENCART_DATABASE_NAME=bitnami_opencart
      - OPENCART_HOST=${APP_HOST}
      - ALLOW_EMPTY_PASSWORD=yes
    labels:
      kompose.service.type: nodeport
    ports:
      - '443'
      - '80:80'
    depends_on:
      - mariadb

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.33.0.0/16